"use client"

import { motion } from "framer-motion"
import { Bot, FileText, Upload } from "lucide-react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"

export function UploadFeatureShowcase() {
  return (
    <div className="grid gap-6 sm:grid-cols-3">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        viewport={{ once: true, margin: "-100px" }}
      >
        <Card className="h-full overflow-hidden">
          <CardHeader className="pb-2">
            <motion.div whileHover={{ scale: 1.05 }} className="text-primary">
              <Upload className="h-10 w-10" />
            </motion.div>
          </CardHeader>
          <CardContent>
            <CardTitle className="text-xl">Upload Your Papers</CardTitle>
            <CardDescription className="mt-2">
              Simply drag and drop your PDF or text documents to get started. Our AI will process your papers and
              extract key information.
            </CardDescription>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        viewport={{ once: true, margin: "-100px" }}
      >
        <Card className="h-full overflow-hidden">
          <CardHeader className="pb-2">
            <motion.div whileHover={{ scale: 1.05 }} className="text-primary">
              <FileText className="h-10 w-10" />
            </motion.div>
          </CardHeader>
          <CardContent>
            <CardTitle className="text-xl">Get AI Summaries</CardTitle>
            <CardDescription className="mt-2">
              Receive comprehensive, structured summaries of your research papers generated by our advanced AI
              technology.
            </CardDescription>
          </CardContent>
        </Card>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        viewport={{ once: true, margin: "-100px" }}
      >
        <Card className="h-full overflow-hidden">
          <CardHeader className="pb-2">
            <motion.div whileHover={{ scale: 1.05 }} className="text-primary">
              <Bot className="h-10 w-10" />
            </motion.div>
          </CardHeader>
          <CardContent>
            <CardTitle className="text-xl">Chat With Your Papers</CardTitle>
            <CardDescription className="mt-2">
              Ask questions about your documents and get specific answers with references to the original text.
            </CardDescription>
          </CardContent>
        </Card>
      </motion.div>
    </div>
  )
}
